### ISSUE TITLE
Hive 3

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#1218]
Support Hive 3.1+

* [ ] Create product-test environments with Hive 3.1 https://github.com/prestosql/presto/issues/190
* [ ] Support Hive managed Transactional/ACID tables https://github.com/prestosql/presto/issues/576
* [ ] TIMESTAMP behaviour does not match sql standard https://github.com/prestosql/presto/issues/37 is related due to https://issues.apache.org/jira/browse/HIVE-12192 "Hive should carry out timestamp computations in UTC"
* [ ] Hive bucket version 2 tables https://github.com/prestosql/presto/issues/1201, https://github.com/prestosql/presto/issues/538
* [ ] Handle Hive's `information_schema` https://github.com/prestosql/presto/issues/1192
* [ ] ...

Related:
* [ ] https://github.com/prestosql/presto/issues/456

**Comment by RugratsJ** [comment]
@findepi, I installed Presto 332 and HDP 3.1, when connecting to Hive and run select queries, I got Original non-ACID files in transactional tables are not supported. What should I do to at lease be able to query (read-only) to Hive 3? Thanks.

**Comment by findepi** [comment]
This is a high-level roadmap issue. Let's keep the discussion high level here only. @RugratsJ  Please ping me on our [slack](https://prestosql.io/slack.html).

**Comment by jiegzhan** [comment]
Added hive-3 missing privileges and principal: 

https://github.com/prestosql/presto/pull/4254

https://github.com/prestosql/presto/pull/4307

**Comment by dain** [comment]
Is HDP end of life (https://endoflife.software/applications/big-data/hortonworks-data-platform-hdp)?  Should we update the title to just Hive3?

**Comment by findepi** [comment]
Trino supports Hive 3 ACID tables for some time now. Of course there are follow-up issues, as always, and these are tracked separately.
This roadmap issue is not being kept up to date as a way to organize future work on the feature.

Good job, everyone involved. 👏
