### ISSUE TITLE
Support complex Hive views

### ISSUE THREAD

**Issue by findepi** [prestosql/presto#5606]
- [x] integrate Coral with Presto https://github.com/prestosql/presto/pull/4661
- [ ] documentation https://github.com/prestosql/presto/issues/4619
- [ ] Improve Calcite shading  https://github.com/prestosql/presto/issues/5604
- [ ] Add tests for Hive view privilege checks https://github.com/prestosql/presto/issues/5605

**Comment by findepi** [comment]
cc @laurachenyu @phd3

**Comment by wmoustafa** [comment]
I think "Support custom UDFS" should refer to #5689 instead.

**Comment by wmoustafa** [comment]
Created [Coral Slack workspace](https://join.slack.com/t/coral-sql/shared_invite/zt-j9jw5idg-mkt3fjA~wgoUEMXXZqMr6g) to discuss the roadmap and the prioritization of those issues. Everyone is welcome to join.

**Comment by wmoustafa** [comment]
@findepi, can we mark which of those issues (maybe in each issue) were encountered in a real use case vs synthetic testing? Can we also ask users to thumb up an issue if they are facing it? This way we can get a sense if the issue was created as part of a validation test, or a real user problem, and how many are interested in it. This will largely guide which issues to prioritize. cc: @martint @electrum @dain

**Comment by findepi** [comment]
> can we mark which of those issues (maybe in each issue) were encountered in a real use case vs synthetic testing?

Thats interesting idea but we never do this. I actually believe edge cases are easier to find by experts in the given technology, so that end users can enjoy peace of mind. 


> Can we also ask users to thumb up an issue if they are facing it?

there is no good way to _ask_ for this, but people may do this nonetheless

**Comment by Manish-starburst** [comment]
Can we link this issue: https://github.com/prestosql/presto/issues/6353
